# docker-compose.yml 基本构造
version: "3"
services: 
  web:
    #reloace username/repo:tag with your name and image 
    image: shanezhiu/get-started:xx-2
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks: 
  webnet: